/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/ModelBeta.glb --printwidth 200 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/ModelBeta.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[-0.016, 2.151, -17.03]} rotation={[Math.PI / 2, 0, 0.337]} scale={1.083} />
        <group name="Sketchfab_model" position={[-14.388, 2.848, 7.098]} rotation={[-Math.PI / 2, 0, 1.424]} scale={[0.1, 0.1, 0.074]}>
          <group name="Root">
            <group name="Cactus_1" scale={[6.182, 6.182, 6.183]} />
          </group>
        </group>
        <group name="Sketchfab_model001" position={[-9.158, 2.941, 9.486]} rotation={[-Math.PI / 2, 0, -0.814]} scale={1.033}>
          <group name="39336dc9cb46483e8d9e86c656fd5660objcleanermaterialmergergle" />
        </group>
        <group name="Sketchfab_model002" position={[-9.523, 2.941, 9.486]} rotation={[-Math.PI / 2, 0, -0.077]} scale={1.033}>
          <group name="39336dc9cb46483e8d9e86c656fd5660objcleanermaterialmerger" />
        </group>
        <group name="Sketchfab_model003" position={[25.621, -1.656, -4.746]} rotation={[-Math.PI / 2, 0, 0]} scale={0.002}>
          <group name="8da83dbbff734e0c83d2519cca3c0851fbx" position={[-0.001, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode" position={[-0.001, 0, 0]}>
              <group name="Camera001" position={[3128.876, 1034.006, -3065.78]} rotation={[-3.14, -0.411, 3.07]}>
                <group name="Object_9" position={[-0.003, 0, 0]} />
              </group>
              <group name="Camera005" position={[-1327.729, 645.464, -340.835]} rotation={[0.162, 1.378, -0.223]} scale={0.692}>
                <group name="Object_9004" position={[0, 0, -0.003]} />
              </group>
              <group name="Camera007" position={[-3708.795, 1517.964, -1683.791]} rotation={[-0.002, 0.058, -0.073]} scale={[1.59, 1.498, 1.59]}>
                <group name="Object_9006" />
              </group>
              <group name="Camera009" position={[5203.794, 1831.818, 4900.756]} rotation={[3.089, -0.463, -2.946]} scale={[1.965, 1.5, 1.673]}>
                <group name="Object_9008" position={[0.002, 0, 0]} rotation={[-1.115, 1.465, 0.973]} />
              </group>
              <group name="Directional_Light" position={[-514.911, 3255.172, -4877.482]} rotation={[2.035, -0.04, 3.047]}>
                <group name="Object_11" position={[0, -0.001, 0.001]} rotation={[Math.PI / 2, 0, 0]}>
                  <group name="Object_12" position={[0.002, 0, 0]} />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model004" position={[25.621, -1.656, -5.67]} rotation={[-Math.PI / 2, 0, -0.746]} scale={0.002}>
          <group name="8da83dbbff734e0c83d2519cca3c0851fbx001" position={[-0.001, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode001">
              <group name="Camera002" position={[3537.851, 1048.904, -1537.696]} rotation={[-3.14, -0.411, 3.07]}>
                <group name="Object_9001" position={[-0.002, 0, 0.002]} />
              </group>
              <group name="Camera006" position={[-2259.418, 706.156, 1440.541]} rotation={[0.149, 1.378, -0.234]} scale={0.692}>
                <group name="Object_9005" />
              </group>
              <group name="Coconut-tree006" position={[3272.002, 732.753, -2338.44]} rotation={[2.877, -0.406, -3.079]} scale={[1.245, 1, 1.043]} />
              <group name="Directional_Light001" position={[-514.911, 3255.172, -4877.483]} rotation={[2.035, -0.04, 3.047]}>
                <group name="Object_11001" position={[0, -0.001, 0]} rotation={[Math.PI / 2, 0, 0]}>
                  <group name="Object_12001" position={[0.001, 0, 0.003]} />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model005" position={[25.458, -1.637, -6.212]} rotation={[-Math.PI / 2, 0, -0.746]} scale={0.001}>
          <group name="8da83dbbff734e0c83d2519cca3c0851fbx002" position={[0.001, -0.003, 0]} rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode002" position={[0, 0, 0.002]}>
              <group name="Camera003" position={[3606.734, 1048.904, -1589.287]} rotation={[-3.03, -0.399, 3.11]} scale={1.255}>
                <group name="Object_9002" position={[16.673, 0, -81.624]} rotation={[-0.092, 0.025, -0.042]} scale={0.775} />
              </group>
              <group name="Directional_Light002" position={[-452.867, 3255.172, -4957.915]} rotation={[1.946, 0.021, 2.988]} scale={0.975}>
                <group name="Object_11002" position={[22.176, 0.002, -82.602]} rotation={[1.564, -0.064, 0.043]} scale={1.275}>
                  <group name="Object_12002" position={[43.943, 0, 20.238]} rotation={[0.071, 0.005, 0.087]} scale={1.331} />
                </group>
              </group>
              <group name="Directional_Light004" position={[1160.638, 3538.839, -1424.455]} rotation={[0.927, 0.071, -0.554]} scale={[1.232, 0.987, 0.983]}>
                <group name="Object_11004" position={[22.178, 0, -82.601]} rotation={[0.312, -1.17, -1.473]} scale={1.275}>
                  <group name="Object_12004" position={[43.941, 0, 20.235]} rotation={[-1.135, -1.158, -1.251]} scale={1.331} />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model006" position={[25.019, -1.882, -7.298]} rotation={[-Math.PI / 2, 0, 0.266]} scale={0.001}>
          <group name="8da83dbbff734e0c83d2519cca3c0851fbx003" position={[0, 0.001, 0]} rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode003" position={[-0.002, 0, 0.001]}>
              <group name="Camera004" position={[3611.946, 1048.903, -1475.91]} rotation={[-3.017, -0.479, 3.044]} scale={0.953}>
                <group name="Object_9003" position={[1.587, 0, -86.571]} rotation={[0.022, 0.008, -0.036]} scale={1.283} />
              </group>
              <group name="Camera008" position={[3073.609, 1048.904, 127.671]} rotation={[-3.025, -0.352, 3.068]} scale={0.748}>
                <group name="Object_9007" position={[63.182, 0.001, 79.876]} rotation={[0.083, 0.02, 0.078]} scale={1.369} />
              </group>
              <group name="Directional_Light003" position={[-514.909, 3255.172, -4877.481]} rotation={[2.035, -0.04, 3.047]}>
                <group name="Object_11003" position={[0.001, 0.001, 0.001]} rotation={[Math.PI / 2, 0, 0]}>
                  <group name="Object_12003" position={[0, 0.001, 0.001]} />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="trees012" />
        <group name="trees024" />
        <group name="trees025" />
        <group name="trees026" />
        <group name="trees027" />
        <group name="trees028" />
        <group name="trees029" />
        <group name="trees030" />
        <group name="trees001" />
        <group name="trees002" />
        <group name="trees003" />
        <group name="trees004" />
        <group name="Armature012" position={[30.545, -1.042, -3.294]} rotation={[-0.199, -0.764, -0.129]} scale={0.635}>
          <primitive object={nodes.Bone} />
          <group name="trees005" />
        </group>
        <group name="trees006" />
        <group name="trees007" />
        <group name="trees008" />
        <mesh
          name="Plane012"
          geometry={nodes.Plane012.geometry}
          material={materials['Material.001']}
          position={[83.208, -1.895, -181.258]}
          rotation={[1.545, 0.02, 0.346]}
          scale={[193.94, 139.548, 93.577]}
        />
        <mesh
          name="old_bg"
          geometry={nodes.old_bg.geometry}
          material={materials['Material.001']}
          position={[35.563, 8.681, -118.854]}
          rotation={[1.594, -0.053, 0.532]}
          scale={[128.566, 101.729, 62.041]}
        />
        <mesh
          name="Plane029"
          geometry={nodes.Plane029.geometry}
          material={materials['Material.002']}
          position={[-20.66, 7.914, 7.355]}
          rotation={[0.536, -0.307, 0.002]}
          scale={[14.382, 9.208, 11.667]}
        />
        <mesh
          name="Plane026"
          geometry={nodes.Plane026.geometry}
          material={materials['Material.002']}
          position={[-4.622, 4.389, 12.748]}
          rotation={[1.547, -0.127, 0.342]}
          scale={[6.008, 3.846, 4.874]}
        />
        <mesh name="Plane027" geometry={nodes.Plane027.geometry} material={materials['Material.002']} position={[1.205, 3.714, 0.55]} rotation={[1.445, 0.002, 0.139]} scale={[10.616, 11.655, 7.05]} />
        <mesh
          name="Plane028"
          geometry={nodes.Plane028.geometry}
          material={materials['Material.002']}
          position={[20.812, 4.112, 9.064]}
          rotation={[1.488, 0.07, 0.784]}
          scale={[18.243, 11.726, 6.453]}
        />
        <mesh
          name="Plane031"
          geometry={nodes.Plane031.geometry}
          material={materials['Material.002']}
          position={[11.572, 6.536, 20.687]}
          rotation={[1.637, -0.016, -0.4]}
          scale={[18.322, 11.731, 14.864]}
        />
        <mesh
          name="Plane033"
          geometry={nodes.Plane033.geometry}
          material={materials['Material.002']}
          position={[-13.591, 4.867, 16.789]}
          rotation={[1.004, -0.325, 0.385]}
          scale={[5.747, 2.89, 3.103]}
        />
        <mesh
          name="Plane034"
          geometry={nodes.Plane034.geometry}
          material={materials['Material.002']}
          position={[-7.656, 4.542, 19.329]}
          rotation={[1.004, -0.325, 0.385]}
          scale={[5.747, 2.89, 3.834]}
        />
        <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials.sand} position={[48.288, -2.603, -17.238]} rotation={[Math.PI, -1.567, Math.PI]} scale={4.298} />
        <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials.sand} position={[48.288, -1.757, -64.814]} rotation={[Math.PI, -0.095, Math.PI]} scale={4.298} />
        <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials.sand} position={[102.725, 0.545, -41.628]} rotation={[0.093, 0.021, 0.036]} />
        <mesh name="Plane025" geometry={nodes.Plane025.geometry} material={materials.sand} position={[102.725, 0.545, -27.086]} rotation={[0.093, 0.021, 0.036]} />
        <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials.sand} position={[91.214, 0.813, -89.131]} rotation={[-3.108, -0.636, 3.031]} scale={[1.451, 0.784, 1.46]} />
        <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials.sand} position={[44.341, -3.504, -114.639]} rotation={[-2.676, 1.51, 2.546]} scale={[1.034, 1.316, 1.029]} />
        <mesh name="Plane008" geometry={nodes.Plane008.geometry} material={materials.sand} position={[1.209, -5.004, -114.467]} rotation={[-1.803, 1.543, 1.672]} scale={[1.366, 1.516, 1.362]} />
        <mesh name="Plane009" geometry={nodes.Plane009.geometry} material={materials.sand} position={[-40.38, -5.351, -114.639]} rotation={[-0.027, 0.006, -0.131]} scale={[1.034, 1.316, 1.029]} />
        <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials.sand} position={[-40.38, -5.351, -51.111]} rotation={[-0.027, 0.006, -0.131]} scale={[1.049, 2.168, 1.029]} />
        <mesh name="Plane011" geometry={nodes.Plane011.geometry} material={materials.sand} position={[-13.766, -1.497, -103.757]} rotation={[-0.027, 0.006, -0.131]} scale={[1.034, 1.316, 1.029]} />
        <mesh
          name="Plane"
          geometry={nodes.Plane.geometry}
          material={materials['Material.003']}
          morphTargetDictionary={nodes.Plane.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane.morphTargetInfluences}
          scale={4.298}
        />
        <mesh
          name="Plane001"
          geometry={nodes.Plane001.geometry}
          material={materials.sand}
          morphTargetDictionary={nodes.Plane001.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane001.morphTargetInfluences}
          position={[-6.375, -0.341, -59.446]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={4.298}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/ModelBeta.glb')
