/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 avengervviron.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/avengervviron.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[-0.016, 2.151, -17.03]} rotation={[Math.PI / 2, 0, 0.337]} scale={1.083} />
        <group name="Sketchfab_model" position={[-14.388, 2.848, 7.098]} rotation={[-Math.PI / 2, 0, 1.424]} scale={[0.1, 0.1, 0.074]}>
          <group name="Root">
            <group name="Cactus_1" scale={[6.182, 6.182, 6.183]} />
          </group>
        </group>
        <group name="Sketchfab_model001" position={[-9.158, 2.941, 9.486]} rotation={[-Math.PI / 2, 0, -0.814]} scale={1.033}>
          <group name="39336dc9cb46483e8d9e86c656fd5660objcleanermaterialmergergle">
            <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.material_0} rotation={[-0.047, 0.109, -0.011]} scale={[1.14, 1.14, 1.045]} />
          </group>
        </group>
        <group name="Sketchfab_model002" position={[-9.523, 2.941, 9.486]} rotation={[-Math.PI / 2, 0, -0.077]} scale={1.033}>
          <group name="39336dc9cb46483e8d9e86c656fd5660objcleanermaterialmerger" />
        </group>
        <group name="Sketchfab_model003" position={[25.621, -1.656, -4.746]} rotation={[-Math.PI / 2, 0, 0]} scale={0.002}>
          <group name="8da83dbbff734e0c83d2519cca3c0851fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode" position={[-0.001, 0, 0]}>
              <group name="Camera001" position={[3128.876, 1034.006, -3065.78]} rotation={[-3.14, -0.411, 3.07]}>
                <group name="Object_9" position={[-0.002, 0, 0.001]} />
              </group>
              <group name="Camera005" position={[-1327.729, 645.464, -340.835]} rotation={[0.162, 1.378, -0.223]} scale={0.692}>
                <group name="Object_9004" position={[0.001, 0, -0.002]} />
              </group>
              <group name="Camera007" position={[-3708.795, 1517.964, -1683.791]} rotation={[-0.002, 0.058, -0.073]} scale={[1.59, 1.498, 1.59]}>
                <group name="Object_9006" />
              </group>
              <group name="Camera009" position={[5203.794, 1831.818, 4900.756]} rotation={[3.089, -0.463, -2.946]} scale={[1.965, 1.5, 1.673]}>
                <group name="Object_9008" position={[0.001, 0, 0]} rotation={[-1.115, 1.465, 0.973]} />
              </group>
              <group name="Coconut-tree" position={[-0.001, 1245, 0]} />
              <group name="Directional_Light" position={[-514.911, 3255.172, -4877.482]} rotation={[2.035, -0.04, 3.047]}>
                <group name="Object_11" position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
                  <group name="Object_12" position={[0.001, 0, 0]} />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model004" position={[25.621, -1.656, -5.67]} rotation={[-Math.PI / 2, 0, -0.746]} scale={0.002}>
          <group name="8da83dbbff734e0c83d2519cca3c0851fbx001" position={[-0.001, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode001">
              <group name="Camera002" position={[3537.851, 1048.904, -1537.696]} rotation={[-3.14, -0.411, 3.07]}>
                <group name="Object_9001" position={[-0.001, 0, 0.001]} />
              </group>
              <group name="Camera006" position={[-2259.418, 706.156, 1440.541]} rotation={[0.149, 1.378, -0.234]} scale={0.692}>
                <group name="Object_9005" position={[0.001, 0, 0]} />
              </group>
              <group name="Coconut-tree001" position={[0, 1245, 0]} />
              <group name="Coconut-tree006" position={[3272.003, 732.753, -2338.44]} rotation={[2.877, -0.406, -3.079]} scale={[1.245, 1, 1.043]} />
              <group name="Directional_Light001" position={[-514.91, 3255.172, -4877.483]} rotation={[2.035, -0.04, 3.047]}>
                <group name="Object_11001" position={[0, -0.001, 0]} rotation={[Math.PI / 2, 0, 0]}>
                  <group name="Object_12001" position={[0.002, 0, 0.002]} />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model005" position={[25.458, -1.637, -6.212]} rotation={[-Math.PI / 2, 0, -0.746]} scale={0.001}>
          <group name="8da83dbbff734e0c83d2519cca3c0851fbx002" position={[0.001, -0.001, 0]} rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode002" position={[0, 0, -0.001]}>
              <group name="Camera003" position={[3606.734, 1048.903, -1589.289]} rotation={[-3.03, -0.399, 3.11]} scale={1.255}>
                <group name="Object_9002" position={[16.674, 0, -81.623]} rotation={[-0.092, 0.025, -0.042]} scale={0.775} />
              </group>
              <group name="Coconut-tree002" position={[0, 1245, -0.001]} />
              <group name="Coconut-tree004" position={[-2186.673, 750.212, -1796.5]} rotation={[-3.104, -0.969, -3.085]} scale={0.692} />
              <group name="Directional_Light002" position={[-452.867, 3255.172, -4957.916]} rotation={[1.946, 0.021, 2.988]} scale={0.975}>
                <group name="Object_11002" position={[22.177, 0.001, -82.602]} rotation={[1.564, -0.064, 0.043]} scale={1.275}>
                  <group name="Object_12002" position={[43.941, 0.001, 20.236]} rotation={[0.071, 0.005, 0.087]} scale={1.331} />
                </group>
              </group>
              <group name="Directional_Light004" position={[1160.638, 3538.839, -1424.458]} rotation={[0.927, 0.071, -0.554]} scale={[1.232, 0.987, 0.983]}>
                <group name="Object_11004" position={[22.177, 0, -82.602]} rotation={[0.312, -1.17, -1.473]} scale={1.275}>
                  <group name="Object_12004" position={[43.94, 0, 20.236]} rotation={[-1.135, -1.158, -1.251]} scale={1.331} />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model006" position={[25.019, -1.882, -7.298]} rotation={[-Math.PI / 2, 0, 0.266]} scale={0.001}>
          <group name="8da83dbbff734e0c83d2519cca3c0851fbx003" position={[0, 0.001, 0]} rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode003">
              <group name="Camera004" position={[3611.946, 1048.903, -1475.911]} rotation={[-3.017, -0.479, 3.044]} scale={0.953}>
                <group name="Object_9003" position={[1.587, 0, -86.567]} rotation={[0.022, 0.008, -0.036]} scale={1.283} />
              </group>
              <group name="Camera008" position={[3073.611, 1048.904, 127.67]} rotation={[-3.025, -0.352, 3.068]} scale={0.748}>
                <group name="Object_9007" position={[63.183, 0, 79.876]} rotation={[0.083, 0.02, 0.078]} scale={1.369} />
              </group>
              <group name="Coconut-tree003" position={[0, 1245, 0.001]} />
              <group name="Coconut-tree005" position={[1005.248, 787.343, -1648.979]} rotation={[-3.083, -0.969, -3.097]} scale={0.692} />
              <group name="Directional_Light003" position={[-514.909, 3255.172, -4877.481]} rotation={[2.035, -0.04, 3.047]}>
                <group name="Object_11003" position={[0.001, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
                  <group name="Object_12003" position={[0, 0, 0]} />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Armature" position={[29.234, -1.429, -6.348]} rotation={[-0.247, -1.198, -0.177]} scale={0.699}>
          <primitive object={nodes.Bone} />
          <group name="trees012">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0002" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0002'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0002'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0002'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0002'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0002_1" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0002_1'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0002_1'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0002_1'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0002_1'].morphTargetInfluences} />
          </group>
        </group>
        <group name="Armature001" position={[26.896, -1.693, -7.433]} rotation={[0.046, -0.053, -0.197]} scale={0.969}>
          <primitive object={nodes.Bone_2} />
          <group name="trees024">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0003" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0003'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0003'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0003'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0003'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0003_1" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0003_1'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0003_1'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0003_1'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0003_1'].morphTargetInfluences} />
          </group>
        </group>
        <group name="Armature002" position={[26.804, -1.338, -8.612]} rotation={[-0.11, 0.575, 0.06]} scale={0.857}>
          <primitive object={nodes.Bone_4} />
          <group name="trees025">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0004" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0004'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0004'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0004'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0004'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0004_1" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0004_1'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0004_1'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0004_1'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0004_1'].morphTargetInfluences} />
          </group>
        </group>
        <group name="Armature003" position={[29.354, -1.104, -7.688]} rotation={[-0.126, -0.748, -0.086]} scale={0.688}>
          <primitive object={nodes.Bone_6} />
          <group name="trees026">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0005" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0005'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0005'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0005'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0005'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0005_1" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0005_1'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0005_1'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0005_1'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0005_1'].morphTargetInfluences} />
          </group>
        </group>
        <group name="Armature004" position={[28.817, -1.042, -8.57]} rotation={[-0.143, -0.008, 0.008]} scale={0.657}>
          <primitive object={nodes.Bone_8} />
          <group name="trees027">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_1" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_1'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_1'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_1'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_1'].morphTargetInfluences} />
          </group>
        </group>
        <group name="Armature005" position={[25.646, -1.271, -11.23]} rotation={[-0.158, 0.947, 0.128]} scale={0.869}>
          <primitive object={nodes.Bone_9} />
          <group name="trees028">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_2" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_2'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_2'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_2'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_2'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_3" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_3'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_3'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_3'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_3'].morphTargetInfluences} />
          </group>
        </group>
        <group name="Armature006" position={[26.483, -1.297, -7.863]} rotation={[-0.106, 0.153, 0.054]} scale={0.586}>
          <primitive object={nodes.Bone_10} />
          <group name="trees029">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_4" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_4'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_4'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_4'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_4'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_5" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_5'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_5'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_5'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_5'].morphTargetInfluences} />
          </group>
        </group>
        <group name="Armature007" position={[27.034, -0.898, -11.166]} rotation={[0.475, 1.093, -0.146]} scale={0.759}>
          <primitive object={nodes.Bone_11} />
          <group name="trees030">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_6" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_6'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_6'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_6'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_6'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_7" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_7'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_7'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_7'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_7'].morphTargetInfluences} />
          </group>
        </group>
        <group name="Armature008" position={[27.393, -1.429, -3.185]} rotation={[0.081, 0.119, -0.046]} scale={0.628}>
          <primitive object={nodes.Bone_1} />
          <group name="trees001">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0002_2" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0002_2'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0002_2'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0002_2'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0002_2'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0002_3" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0002_3'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0002_3'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0002_3'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0002_3'].morphTargetInfluences} />
          </group>
        </group>
        <group name="Armature009" position={[29.063, -1.693, -4.054]} rotation={[0.051, -0.465, -0.177]} scale={0.666}>
          <primitive object={nodes.Bone_3} />
          <group name="trees002">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0003_2" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0003_2'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0003_2'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0003_2'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0003_2'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0003_3" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0003_3'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0003_3'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0003_3'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0003_3'].morphTargetInfluences} />
          </group>
        </group>
        <group name="Armature010" position={[29.784, -1.338, -5.261]} rotation={[-0.096, 0.29, 0.027]} scale={0.694}>
          <primitive object={nodes.Bone_5} />
          <group name="trees003">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0004_2" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0004_2'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0004_2'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0004_2'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0004_2'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0004_3" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0004_3'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0004_3'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0004_3'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0004_3'].morphTargetInfluences} />
          </group>
        </group>
        <group name="Armature011" position={[29.259, -1.104, -2.096]} rotation={[-2.991, -0.914, -3.022]} scale={0.984}>
          <primitive object={nodes.Bone_7} />
          <group name="trees004">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0005_2" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0005_2'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0005_2'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0005_2'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0005_2'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0005_3" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0005_3'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0005_3'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0005_3'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0005_3'].morphTargetInfluences} />
          </group>
        </group>
        <group name="Armature012" position={[30.545, -1.042, -3.294]} rotation={[-0.199, -0.764, -0.129]} scale={0.635}>
          <primitive object={nodes.Bone_12} />
          <group name="trees005">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_8" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_8'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_8'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_8'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_8'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_9" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_9'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_9'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_9'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_9'].morphTargetInfluences} />
          </group>
        </group>
        <group name="Armature013" position={[28.543, -1.271, -7.774]} rotation={[-0.571, -1.4, -0.564]} scale={0.6}>
          <primitive object={nodes.Bone_13} />
          <group name="trees006">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_10" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_10'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_10'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_10'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_10'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_11" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_11'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_11'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_11'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_11'].morphTargetInfluences} />
          </group>
        </group>
        <group name="Armature014" position={[29.488, -1.297, -4.369]} rotation={[-0.112, 0.357, 0.077]} scale={0.929}>
          <primitive object={nodes.Bone_14} />
          <group name="trees007">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_12" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_12'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_12'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_12'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_12'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_13" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_13'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_13'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_13'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_13'].morphTargetInfluences} />
          </group>
        </group>
        <group name="Armature015" position={[29.93, -0.936, -6.09]} rotation={[0.213, -0.104, 0.304]} scale={0.86}>
          <primitive object={nodes.Bone_15} />
          <group name="trees008">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_14" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_14'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_14'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_14'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_14'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_15" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_15'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_15'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_15'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_15'].morphTargetInfluences} />
          </group>
        </group>
        <mesh name="tripo_node_afaf7fab-f38a-4a5b-a940-e211ad04a008" geometry={nodes['tripo_node_afaf7fab-f38a-4a5b-a940-e211ad04a008'].geometry} material={materials['tripo_material_afaf7fab-f38a-4a5b-a940-e211ad04a008']} position={[-14.136, 4.501, 8.88]} scale={3.686} />
        <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Procedural Water Surface']} position={[17.951, -2.014, -8.31]} rotation={[0, -1.562, 0]} scale={[3.271, 3.271, 5.328]} />
        <mesh name="Plane012" geometry={nodes.Plane012.geometry} material={materials.Material} position={[83.208, -1.895, -181.258]} rotation={[1.545, 0.02, 0.346]} scale={[193.94, 139.548, 93.577]} />
        <mesh name="old_bg" geometry={nodes.old_bg.geometry} material={materials.Material} position={[35.563, 8.681, -118.854]} rotation={[1.594, -0.053, 0.532]} scale={[128.566, 101.729, 62.041]} />
        <mesh name="Plane029" geometry={nodes.Plane029.geometry} material={materials['Material.002']} position={[-20.66, 7.914, 7.355]} rotation={[0.536, -0.307, 0.002]} scale={[14.382, 9.208, 11.667]} />
        <mesh name="Plane026" geometry={nodes.Plane026.geometry} material={materials['Material.002']} position={[-4.622, 4.389, 12.748]} rotation={[1.547, -0.127, 0.342]} scale={[6.008, 3.846, 4.874]} />
        <mesh name="Plane027" geometry={nodes.Plane027.geometry} material={materials['Material.002']} position={[1.205, 3.714, 0.55]} rotation={[1.445, 0.002, 0.139]} scale={[10.616, 11.655, 7.05]} />
        <mesh name="Plane028" geometry={nodes.Plane028.geometry} material={materials['Material.002']} position={[20.812, 4.112, 9.064]} rotation={[1.488, 0.07, 0.784]} scale={[18.243, 11.726, 6.453]} />
        <mesh name="Plane031" geometry={nodes.Plane031.geometry} material={materials['Material.002']} position={[11.572, 6.536, 20.687]} rotation={[1.637, -0.016, -0.4]} scale={[18.322, 11.731, 14.864]} />
        <mesh name="Plane033" geometry={nodes.Plane033.geometry} material={materials['Material.002']} position={[-13.591, 4.867, 16.789]} rotation={[1.004, -0.325, 0.385]} scale={[5.747, 2.89, 3.103]} />
        <mesh name="Plane034" geometry={nodes.Plane034.geometry} material={materials['Material.002']} position={[-7.656, 4.542, 19.329]} rotation={[1.004, -0.325, 0.385]} scale={[5.747, 2.89, 3.834]} />
        <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials.sand} position={[48.288, -2.603, -17.238]} rotation={[Math.PI, -1.567, Math.PI]} scale={4.298} />
        <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials.sand} position={[48.288, -1.757, -64.814]} rotation={[Math.PI, -0.095, Math.PI]} scale={4.298} />
        <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials.sand} position={[102.725, 0.545, -41.628]} rotation={[0.093, 0.021, 0.036]} />
        <mesh name="Plane025" geometry={nodes.Plane025.geometry} material={materials.sand} position={[102.725, 0.545, -27.086]} rotation={[0.093, 0.021, 0.036]} />
        <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials.sand} position={[91.214, 0.813, -89.131]} rotation={[-3.108, -0.636, 3.031]} scale={[1.451, 0.784, 1.46]} />
        <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials.sand} position={[44.341, -3.504, -114.639]} rotation={[-2.676, 1.51, 2.546]} scale={[1.034, 1.316, 1.029]} />
        <mesh name="Plane008" geometry={nodes.Plane008.geometry} material={materials.sand} position={[1.209, -5.004, -114.467]} rotation={[-1.803, 1.543, 1.672]} scale={[1.366, 1.516, 1.362]} />
        <mesh name="Plane009" geometry={nodes.Plane009.geometry} material={materials.sand} position={[-40.38, -5.351, -114.639]} rotation={[-0.027, 0.006, -0.131]} scale={[1.034, 1.316, 1.029]} />
        <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials.sand} position={[-40.38, -5.351, -51.111]} rotation={[-0.027, 0.006, -0.131]} scale={[1.049, 2.168, 1.029]} />
        <mesh name="Plane011" geometry={nodes.Plane011.geometry} material={materials.sand} position={[-13.766, -1.497, -103.757]} rotation={[-0.027, 0.006, -0.131]} scale={[1.034, 1.316, 1.029]} />
        <mesh name="Plane013" geometry={nodes.Plane013.geometry} material={materials['Procedural Water Surface']} morphTargetDictionary={nodes.Plane013.morphTargetDictionary} morphTargetInfluences={nodes.Plane013.morphTargetInfluences} position={[21.475, -1.613, -5.666]} scale={3.814} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.001']} morphTargetDictionary={nodes.Plane.morphTargetDictionary} morphTargetInfluences={nodes.Plane.morphTargetInfluences} scale={4.298} />
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.sand} morphTargetDictionary={nodes.Plane001.morphTargetDictionary} morphTargetInfluences={nodes.Plane001.morphTargetInfluences} position={[-6.375, -0.341, -59.446]} rotation={[Math.PI, 0, Math.PI]} scale={4.298} />
      </group>
    </group>
  )
}

useGLTF.preload('/avengervviron.glb')
