/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 avengervviron.glb 
*/

import React, {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
} from 'react'
import { useFrame, useGraph } from '@react-three/fiber'
import { Html, useCursor, useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { useTexture } from '@react-three/drei'
import {
  PROTOTYPE_HOVER_DESERT_BUSH,
  PROTOTYPE_HOVER_OASIS_POOL,
  PROTOTYPE_HOVER_SAGUARO_EXTRA_1,
  PROTOTYPE_HOVER_SAGUARO_EXTRA_2,
  PROTOTYPE_HOVER_SAGUARO_PRIMARY,
} from '../constants/prototypeHoverCopy'
import {
  Color,
  Euler,
  RepeatWrapping,
  MeshBasicMaterial,
  MeshDepthMaterial,
  MeshPhysicalMaterial,
  MeshStandardMaterial,
} from 'three'
import { getRevealT } from '../store/revealProgressStore'
import { useTopNavStore } from '../store/useTopNavStore'
import {
  easeInOutCubic,
  phaseObjectWindow,
  REVEAL_PHASES,
} from '../constants/revealTimeline'
import { RevealLabel3D } from './RevealLabel3D'
import {
  HOVER_HTML_DISTANCE_FACTOR,
  HOVER_STACKED_FONT_SCALE,
} from '../constants/hoverUi'

/* Per-phase object reveal windows derived from REVEAL_PHASES — keeps DeferredRevealGroup ramps
 * aligned with each phase's label-out → object-in transition. */
const MIND_WINDOW = phaseObjectWindow(REVEAL_PHASES.mind)
const BODY_WINDOW = phaseObjectWindow(REVEAL_PHASES.body)
const HEART_WINDOW = phaseObjectWindow(REVEAL_PHASES.heart)

/**
 * avengervviron.glb embeds duplicate ArmatureAction / Key.005Action clips; playing them all
 * reads as a broken loop. Coconut palms use procedural wind on `PalmWindArmature` instead.
 */

const HOVER_HIDE_MS = 240

/** Tunable procedural breeze on palm armature groups (local rotation offset, rad). */
const PALM_WIND = {
  /** Peak angular offset after smoothing (keep small — reads as mass + airflow). */
  ampMainRad: 0.034,
  ampCrossRad: 0.023,
  ampYawRad: 0.016,
  /**
   * Inertial smoothing (seconds). Higher = heavier crowns, less jitter, slower response.
   * Removes the "metronome" feel of raw sines.
   */
  inertiaTauSec: 1.35,
  /** Per-tree decorrelation (golden ratio). */
  phaseSpread: 2.3999632297286533,
  /**
   * Slow, incommensurate frequencies (Hz) — layered so motion never quite repeats on a 2–3s loop.
   * Keep low (~0.05–0.25) so it reads as wind, not vibration.
   */
  fA: 0.092,
  fB: 0.148,
  fC: 0.241,
  /** Ultra-slow amplitude / bias drift (breathing gusts, ~25–40s scale). */
  fDrift: 0.028,
  driftAmount: 0.28,
}

/**
 * Sum of detuned sines — cheap quasi-turbulent flow without obvious period.
 * `weights` sum to ~1 for a typical -1..1 range before scaling.
 */
function flowScalar(t, phase, weights, freqs) {
  const tau = Math.PI * 2
  return (
    weights[0] * Math.sin(tau * freqs[0] * t + phase) +
    weights[1] * Math.sin(tau * freqs[1] * t + phase * 1.713) +
    weights[2] * Math.sin(tau * freqs[2] * t + phase * 2.417)
  )
}

/** Parent-level sway: smoothed, multi-band airflow (not synced to-and-fro). */
function PalmWindArmature({ swayIndex, name, children, ...props }) {
  const ref = useRef(null)
  const baseEulerRef = useRef(new Euler())
  const capturedRef = useRef(false)
  /** Smoothed offset from base (inertial follow — kills high-frequency shiver). */
  const offRef = useRef({ x: 0, y: 0, z: 0 })

  useLayoutEffect(() => {
    const g = ref.current
    if (!g) return
    baseEulerRef.current.copy(g.rotation)
    capturedRef.current = true
    offRef.current = { x: 0, y: 0, z: 0 }
  }, [])

  useFrame(({ clock }, delta) => {
    const g = ref.current
    if (!g || !capturedRef.current) return
    const t = clock.getElapsedTime()
    const phase = swayIndex * PALM_WIND.phaseSpread
    const w = PALM_WIND

    const drift =
      1 +
      w.driftAmount *
        (0.5 + 0.5 * Math.sin(Math.PI * 2 * w.fDrift * t + phase * 0.37))

    const wx = [0.42, 0.33, 0.25]
    const wz = [0.48, 0.3, 0.22]
    const wy = [0.35, 0.38, 0.27]

    // Orthogonal flow mixes different phase ratios so axes are not a Lissajous loop.
    const fx = flowScalar(t, phase + 0.61, wx, [w.fA, w.fB, w.fC])
    const fz = flowScalar(t, phase, wz, [w.fB * 0.97, w.fC * 1.03, w.fA * 1.11])
    const fy = flowScalar(t, phase + 1.27, wy, [w.fC, w.fA * 1.07, w.fB * 0.91])

    const tx = w.ampCrossRad * fx * drift
    const ty = w.ampYawRad * fy * drift
    const tz = w.ampMainRad * fz * drift

    const k = 1 - Math.exp(-delta / w.inertiaTauSec)
    const o = offRef.current
    o.x += (tx - o.x) * k
    o.y += (ty - o.y) * k
    o.z += (tz - o.z) * k

    const bx = baseEulerRef.current.x
    const by = baseEulerRef.current.y
    const bz = baseEulerRef.current.z
    g.rotation.x = bx + o.x
    g.rotation.y = by + o.y
    g.rotation.z = bz + o.z
  })

  return (
    <group ref={ref} name={name} {...props}>
      {children}
    </group>
  )
}

const RevealGroupBatchContext = createContext(null)

/** One useFrame applies all staged reveal groups — single `getRevealT()` read per frame. */
function RevealGroupBatchRoot({ children }) {
  const gettersRef = useRef(new Set())

  const register = useCallback((getSnapshot) => {
    gettersRef.current.add(getSnapshot)
    return () => {
      gettersRef.current.delete(getSnapshot)
    }
  }, [])

  useFrame(() => {
    const t = getRevealT()
    for (const getSnapshot of gettersRef.current) {
      const snap = getSnapshot()
      if (!snap) continue
      const {
        groupRef,
        active,
        rampStart,
        rampDuration,
        scaleFrom,
        scaleTo,
        yLift,
        warmVisible,
      } = snap
      const g = groupRef.current
      if (!g) continue
      const scaleSpan = scaleTo - scaleFrom
      if (!active) {
        g.visible = false
        g.scale.setScalar(1)
        g.position.y = 0
        continue
      }
      const u = Math.max(0, Math.min(1, (t - rampStart) / rampDuration))
      const e = easeInOutCubic(u)
      g.visible = warmVisible ? true : e > 0.003
      g.scale.setScalar(scaleFrom + scaleSpan * e)
      g.position.y = -yLift * (1 - e)
    }
  })

  return (
    <RevealGroupBatchContext.Provider value={register}>{children}</RevealGroupBatchContext.Provider>
  )
}

/** Staggered scale-in for trees / oasis — registers with RevealGroupBatchRoot (must be under provider). */
function DeferredRevealGroup({
  active,
  rampStart = 0,
  rampDuration = 0.5,
  yLift = 0.06,
  scaleFrom = 0.92,
  scaleTo = 1,
  /** If true, group stays visible while active (no visibility pop) — for heavy skinned palms. */
  warmVisible = false,
  name: groupName,
  children,
}) {
  const ref = useRef(null)
  const register = useContext(RevealGroupBatchContext)
  const propsRef = useRef({
    active,
    rampStart,
    rampDuration,
    scaleFrom,
    scaleTo,
    yLift,
    warmVisible,
  })
  propsRef.current = {
    active,
    rampStart,
    rampDuration,
    scaleFrom,
    scaleTo,
    yLift,
    warmVisible,
  }

  useLayoutEffect(() => {
    if (!register) return undefined
    const getSnapshot = () => ({
      groupRef: ref,
      ...propsRef.current,
    })
    return register(getSnapshot)
  }, [register])

  return (
    <group ref={ref} name={groupName}>
      {children}
    </group>
  )
}

/** Hover label in mesh-local space; `onHoverChange` drives scene-level cursor feedback */
export function HoverMesh({
  label,
  /** Small line above title (stacked chip only) */
  detail,
  /** Between headline and CTA — matches prototype `.tt-sub` (e.g. Second Skin, Liquid Gold) */
  chipSubline,
  /** Bottom CTA strip, e.g. Enter (stacked chip only) */
  ctaLabel,
  /** After Enter — matches prototype `.tt-note` (e.g. Truth recommendation line) */
  chipFootnote,
  /** `stacked` = detail + bold headline + optional CTA — richer than single-line chip */
  chipStyle = 'default',
  /** Stacked layout only — max width of the chip (px). */
  stackedMaxWidth,
  /** Stacked layout only — multiply all stacked font sizes (e.g. 0.85 for smaller type). */
  stackedFontScale = HOVER_STACKED_FONT_SCALE,
  /** Stacked layout only — outer chip padding (e.g. tighter vertical). */
  stackedPadding,
  /** Stacked layout only — gap between stacked text rows (px). */
  stackedRowGap,
  /** Stacked layout only — tighter divider + Enter row (less vertical height). */
  stackedEnterCompact = false,
  /**
   * Optional idle/hover chrome for the chip (e.g. moon: grey text on light panel → black on white).
   * When omitted, keeps transparent + white outline until hover, then white fill + dark text.
   */
  chipPalette,
  /** `fixed` keeps constant screen-size labels; `distance` preserves depth-based scaling. */
  screenSizeMode = 'fixed',
  htmlPosition = [0, 2, 0],
  distanceFactor = HOVER_HTML_DISTANCE_FACTOR,
  onHoverChange,
  onSelect,
  children,
}) {
  const [show, setShow] = useState(false)
  const [chipHover, setChipHover] = useState(false)
  const meshInsideRef = useRef(false)
  const labelInsideRef = useRef(false)
  const hideTimerRef = useRef(null)
  /* Hide hover chip while About is the active page so a stale chip can't survive a mid-hover navigation. */
  const aboutOpen = useTopNavStore((s) => s.aboutOpen)

  const clearHideTimer = () => {
    if (hideTimerRef.current != null) {
      clearTimeout(hideTimerRef.current)
      hideTimerRef.current = null
    }
  }

  const scheduleHide = () => {
    clearHideTimer()
    hideTimerRef.current = window.setTimeout(() => {
      hideTimerRef.current = null
      if (!meshInsideRef.current && !labelInsideRef.current) {
        setShow(false)
        setChipHover(false)
        onHoverChange?.(false)
      }
    }, HOVER_HIDE_MS)
  }

  useEffect(() => () => clearHideTimer(), [])

  const stackedMw = stackedMaxWidth ?? (chipStyle === 'stacked' ? 300 : undefined)
  const fs = chipStyle === 'stacked' ? stackedFontScale : 1
  const htmlScaleProps =
    screenSizeMode === 'distance'
      ? { transform: true, distanceFactor }
      : { transform: false }
  const outerPad =
    chipStyle === 'stacked' ? stackedPadding ?? '10px 20px 12px' : '9px 14px 7px'
  const stackGap = stackedRowGap ?? 6

  const chipBg = chipPalette
    ? chipHover
      ? chipPalette.hoverBackground
      : chipPalette.idleBackground
    : chipHover
      ? '#ffffff'
      : 'transparent'
  const chipFg = chipPalette
    ? chipHover
      ? chipPalette.hoverColor
      : chipPalette.idleColor
    : chipHover
      ? '#111111'
      : '#ffffff'
  const chipBorder = chipPalette
    ? chipHover
      ? chipPalette.hoverBorder ?? '1px solid rgba(0,0,0,0.22)'
      : chipPalette.idleBorder ?? '1px solid rgba(0,0,0,0.12)'
    : '1px solid #ffffff'
  const chipShadow = chipPalette
    ? chipHover
      ? chipPalette.hoverBoxShadow ?? '0 4px 22px rgba(0,0,0,0.14)'
      : chipPalette.idleBoxShadow ?? '0 2px 14px rgba(0,0,0,0.08)'
    : chipHover
      ? '0 0 20px rgba(255, 255, 255, 0.93)'
      : '0 2px 16px rgba(0, 0, 0, 0.35)'

  const child = React.Children.only(children)
  const existing = child.props.children
  return React.cloneElement(child, {
    ...child.props,
    onPointerOver: (e) => {
      child.props.onPointerOver?.(e)
      e.stopPropagation()
      meshInsideRef.current = true
      clearHideTimer()
      setShow(true)
      onHoverChange?.(true)
    },
    onPointerOut: (e) => {
      child.props.onPointerOut?.(e)
      meshInsideRef.current = false
      scheduleHide()
    },
    onClick: (e) => {
      child.props.onClick?.(e)
      e.stopPropagation()
      onSelect?.(e)
    },
    children: (
      <>
        {existing}
        {show && !aboutOpen && (
          <Html
            position={htmlPosition}
            center
            {...htmlScaleProps}
            style={{ pointerEvents: 'none', userSelect: 'none' }}
          >
            <div
              role={onSelect ? 'button' : undefined}
              tabIndex={onSelect ? 0 : undefined}
              onPointerEnter={() => {
                labelInsideRef.current = true
                setChipHover(true)
                clearHideTimer()
              }}
              onPointerLeave={() => {
                labelInsideRef.current = false
                setChipHover(false)
                scheduleHide()
              }}
              onClick={(e) => {
                e.stopPropagation()
                onSelect?.(e)
              }}
              onKeyDown={(e) => {
                if (!onSelect) return
                if (e.key === 'Enter' || e.key === ' ') {
                  e.preventDefault()
                  onSelect(e)
                }
              }}
              style={{
                pointerEvents: 'auto',
                cursor: onSelect ? 'pointer' : 'default',
                display: 'inline-flex',
                alignItems: 'center',
                justifyContent: 'center',
                background: chipBg,
                color: chipFg,
                padding: outerPad,
                borderRadius: chipHover ? 25 : 10,
                fontSize: chipStyle === 'stacked' ? 12 * fs : 12,
                fontWeight: 400,
                lineHeight: chipStyle === 'stacked' ? 1.2 : 1.12,
                letterSpacing: '0.02em',
                border: chipBorder,
                boxShadow: chipShadow,
                whiteSpace: chipStyle === 'stacked' ? 'normal' : 'nowrap',
                fontFamily: "'Requiem Fine HTF Roman', serif",
                transition:
                  'background 0.15s ease, color 0.15s ease, box-shadow 0.3s ease, border-radius 0.3s ease',
                textAlign: chipStyle === 'stacked' ? 'center' : 'left',
                maxWidth: stackedMw,
              }}
            >
              {chipStyle === 'stacked' ? (
                <span
                  style={{
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'center',
                    gap: stackGap,
                  }}
                >
                  {detail ? (
                    <span
                      style={{
                        fontSize: 9 * fs,
                        fontWeight: 500,
                        letterSpacing: '0.14em',
                        textTransform: 'uppercase',
                        opacity: chipHover ? 0.65 : 0.82,
                        lineHeight: 1.35,
                      }}
                    >
                      {detail}
                    </span>
                  ) : null}
                  <span
                    style={{
                      fontSize: 14 * fs,
                      fontWeight: 700,
                      letterSpacing: '0.06em',
                      lineHeight: 1.15,
                      whiteSpace: 'nowrap',
                    }}
                  >
                    {label}
                  </span>
                  {chipSubline ? (
                    <span
                      style={{
                        fontSize: 10 * fs,
                        fontWeight: 400,
                        letterSpacing: '0.12em',
                        lineHeight: 1.35,
                        opacity: chipHover ? 0.55 : 0.72,
                      }}
                    >
                      {chipSubline}
                    </span>
                  ) : null}
                  {ctaLabel ? (
                    <span
                      style={{
                        display: 'block',
                        width: '100%',
                        marginTop: stackedEnterCompact ? 0 : 2,
                        paddingTop: stackedEnterCompact ? 5 : 8,
                        borderTop: `1px solid ${
                          chipPalette
                            ? chipHover
                              ? 'rgba(0,0,0,0.2)'
                              : 'rgba(0,0,0,0.14)'
                            : chipHover
                              ? 'rgba(17,17,17,0.2)'
                              : 'rgba(255,255,255,0.38)'
                        }`,
                        fontSize: 10 * fs,
                        fontWeight: 700,
                        letterSpacing: '0.26em',
                        textTransform: 'uppercase',
                        color: chipHover
                          ? chipPalette
                            ? 'rgba(25,25,25,0.98)'
                            : '#ffffff'
                          : 'inherit',
                        textShadow: chipHover
                          ? chipPalette
                            ? '0 0 14px rgba(255,255,255,0.72)'
                            : '0 0 22px rgba(255,255,255,0.98)'
                          : 'none',
                        transition: 'color 0.15s ease, text-shadow 0.2s ease',
                      }}
                    >
                      {ctaLabel}
                    </span>
                  ) : null}
                  {chipFootnote ? (
                    <span
                      style={{
                        display: 'block',
                        width: '100%',
                        marginTop: 6,
                        fontSize: 8 * fs,
                        fontStyle: 'italic',
                        fontWeight: 400,
                        letterSpacing: '0.12em',
                        lineHeight: 1.45,
                        color: chipHover ? 'rgba(90, 70, 40, 0.72)' : 'rgba(196, 151, 74, 0.52)',
                      }}
                    >
                      {chipFootnote}
                    </span>
                  ) : null}
                </span>
              ) : (
                label
              )}
            </div>
          </Html>
        )}
      </>
    ),
  })
}

export function DesertGlb({ showFoliage = true, onHoverSelect, ...props }) {
  const group = React.useRef()
  const [hoverUi, setHoverUi] = useState(false)
  useCursor(hoverUi, 'pointer')
  const { scene } = useGLTF('/ModelBeta.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  /* JSX builds meshes under `group`, not the detached `clone` graph — shadow flags must apply here */
  useLayoutEffect(() => {
    const applyShadows = () => {
      const root = group.current
      if (!root) return
      root.traverse((obj) => {
        if (obj.isLight) obj.visible = false
        if (obj.isCamera) obj.visible = false
        if (obj.isMesh || obj.isSkinnedMesh) {
          obj.castShadow = true
          obj.receiveShadow = true
        }
        if (obj.isSkinnedMesh) obj.frustumCulled = false
      })
    }
    applyShadows()
    const id = requestAnimationFrame(applyShadows)
    return () => cancelAnimationFrame(id)
  }, [])

  /** Cutout shadows for foliage (desert bush + saguaro); upgrade Basic materials so sun + shadow map behave correctly */
  useEffect(() => {
    const run = () => {
      const VEG_KEYS = [
        'Cononute_tree-Leafs',
        'tripo_material_afaf7fab-f38a-4a5b-a940-e211ad04a008',
        'material_0',
      ]

      const replaceMaterialOnScene = (oldMat, newMat) => {
        const root = group.current
        if (!root) return
        root.traverse((o) => {
          if (!o.isMesh && !o.isSkinnedMesh) return
          const mats = Array.isArray(o.material) ? o.material : [o.material]
          const next = mats.map((mat) => (mat === oldMat ? newMat : mat))
          o.material = Array.isArray(o.material) ? next : next[0]
        })
      }

      for (const key of VEG_KEYS) {
        const m = materials[key]
        if (!m) continue

        if (m.isMeshBasicMaterial) {
          const isTripo = key.includes('tripo')
          const std = new MeshStandardMaterial({
            map: m.map,
            color: m.color ? m.color.clone() : 0xffffff,
            side: m.side,
            roughness: isTripo ? 0.92 : 0.88,
            metalness: 0,
            envMapIntensity: isTripo ? 0.22 : 0.4,
          })
          if (m.map) {
            std.transparent = false
            std.alphaTest = 0.42
            std.depthWrite = true
          }
          replaceMaterialOnScene(m, std)
          m.dispose()
          materials[key] = std
          continue
        }

        if (m.map || m.alphaMap) {
          m.transparent = false
          m.alphaTest = 0.42
          m.depthWrite = true
          m.needsUpdate = true
        }
      }
    }
    run()
    const id = requestAnimationFrame(run)
    return () => cancelAnimationFrame(id)
  }, [materials])

  /** Alpha-tested meshes must use matching depth material or they cast solid shadow silhouettes / none. */
  useEffect(() => {
    const root = group.current
    if (!root) return
    const run = () => {
      root.traverse((o) => {
        if (!o.isMesh || o.isSkinnedMesh) return
        const mat = Array.isArray(o.material) ? o.material[0] : o.material
        if (!mat || mat.alphaTest == null || mat.alphaTest <= 0) return
        if (o.customDepthMaterial) {
          o.customDepthMaterial.dispose()
          o.customDepthMaterial = undefined
        }
        const dm = new MeshDepthMaterial({
          map: mat.map,
          alphaMap: mat.alphaMap,
          alphaTest: mat.alphaTest,
          depthWrite: true,
        })
        o.customDepthMaterial = dm
      })
    }
    run()
    const id = requestAnimationFrame(run)
    return () => {
      cancelAnimationFrame(id)
      root.traverse((o) => {
        if (o.customDepthMaterial) {
          o.customDepthMaterial.dispose()
          o.customDepthMaterial = undefined
        }
      })
    }
  }, [materials])

  // GLB exports sand at ~roughness 1 — reads flat under any sun; lower for directional + specular on ripples
  useEffect(() => {
    // ModelBeta.glb uses 'Material.003' for main sand plane and 'sand' for background sand planes
    for (const key of ['Material.003', 'sand', 'Material.001']) {
      const m = materials[key]
      if (m && 'roughness' in m) {
        m.roughness = 0.74
        m.metalness = 0
        m.envMapIntensity = 0.52
      }
    }
  }, [materials])
  /** Sand morph sync: only `Plane` + `Plane.001` carry morph targets in the GLB (see Blender object "Plane"). */
  const sandMorphPlaneRef = useRef(null)
  const sandMorphPlane001Ref = useRef(null)

  const sandTexture = useTexture('/sand.jpg')  // put sand.jpg in your /public folder

  sandTexture.wrapS = sandTexture.wrapT = RepeatWrapping
  sandTexture.repeat.set(10, 10)  // adjust tiling amount to taste

  const sandTerrainMatProps = useMemo(
    () => ({
      map: sandTexture,
      roughness: 0.78,
      metalness: 0,
      bumpMap: sandTexture,
      bumpScale: 0.075,
      envMapIntensity: 0.52,
    }),
    [sandTexture],
  )

  /** Replaces GLB procedural water (too transparent over sand); opaque pool + spec for B/W + HDR env */
  const oasisWaterMat = useMemo(() => {
    const m = new MeshPhysicalMaterial({
      color: new Color('#1c2a32'),
      roughness: 0.12,
      metalness: 0.04,
      envMapIntensity: 0.62,
      transparent: false,
      opacity: 1,
      depthWrite: true,
      clearcoat: 0.45,
      clearcoatRoughness: 0.22,
      transmission: 0,
      thickness: 0,
    })
    return m
  }, [])

  useEffect(() => {
    return () => oasisWaterMat.dispose()
  }, [oasisWaterMat])

  useFrame(({ clock }, delta) => {
    const t = clock.getElapsedTime()

    // Horizontal drift: scroll UVs so ripples move along the sand (not "pumping" vertically)
    sandTexture.offset.x -= delta * 0.024
    const mainMap = materials['Material.003']?.map || materials['Material.001']?.map
    if (mainMap) mainMap.offset.x -= delta * 0.017

    // Morph: one shape key "Key 1" is authored as vertical-ish in Blender — use smooth sin (no |sin|),
    // low amplitude so motion reads as subtle breathe, dominated by UV drift above
    const morphAmp = 0.2
    const w = morphAmp * (0.5 + 0.5 * Math.sin(t * 0.42))
    const m0 = sandMorphPlaneRef.current
    if (m0?.morphTargetInfluences?.length) m0.morphTargetInfluences[0] = w
    const m1 = sandMorphPlane001Ref.current
    if (m1?.morphTargetInfluences?.length) m1.morphTargetInfluences[0] = w
  })

  return (
  <group ref={group} {...props} position={[1, -5.9, -16.9]} rotation={[0, 0.55, 0]} dispose={null}>
      <RevealGroupBatchRoot>
      <group name="Scene">
        <group name="Empty" position={[-0.016, 2.151, -17.03]} rotation={[Math.PI / 2, 0, 0.337]} scale={1.083} />
        {/* Realm labels moved to DesertScene.jsx for consistent camera-attached positioning */}
        {/* COMMENTED OUT: Bush and Cactus objects removed from ModelBeta.glb
        <DeferredRevealGroup
          active={showFoliage}
          rampStart={MIND_WINDOW.rampStart}
          rampDuration={MIND_WINDOW.rampDuration}
          name="bush-reveal"
        >
          <group name="Sketchfab_model" position={[-14.388, 2.848, 7.098]} rotation={[-Math.PI / 2, 0, 1.424]} scale={[0.1, 0.1, 0.074]}>
            <group name="Root">
              <group name="Cactus_1" scale={[6.182, 6.182, 6.183]} />
            </group>
          </group>
          <group name="Sketchfab_model001" position={[-8.75, 2.941, 15.486]} rotation={[-Math.PI / 2, 0, -0.814]} scale={1.033}>
            <group name="39336dc9cb46483e8d9e86c656fd5660objcleanermaterialmergergle">
              <HoverMesh
                label={PROTOTYPE_HOVER_DESERT_BUSH.realm}
                chipStyle="stacked"
                screenSizeMode="fixed"
                htmlPosition={[-1.70, 1.65, 0.15]}
                onHoverChange={setHoverUi}
                onSelect={() => onHoverSelect?.(PROTOTYPE_HOVER_DESERT_BUSH)}
              >
                <mesh name="desert_bush_sketchfab" geometry={nodes.Object_2.geometry} material={materials.material_0} rotation={[-0.047, 0.109, -0.011]} scale={[1.14, 1.14, 1.045]} />
              </HoverMesh>
            </group>
          </group>
        </DeferredRevealGroup>
        <DeferredRevealGroup
          active={showFoliage}
          rampStart={BODY_WINDOW.rampStart}
          rampDuration={BODY_WINDOW.rampDuration}
          name="cactus-reveal"
        >
          <HoverMesh
            label={PROTOTYPE_HOVER_SAGUARO_EXTRA_1.realm}
            chipStyle="stacked"
            screenSizeMode="fixed"
            htmlPosition={[0.52, 0.38, 0]}
            stackedMaxWidth={340}
            stackedPadding="12px 24px 14px"
            onHoverChange={setHoverUi}
            onSelect={() => onHoverSelect?.(PROTOTYPE_HOVER_SAGUARO_EXTRA_1)}
          >
            <mesh
              name="tripo_saguaro_extra_1"
              geometry={nodes['tripo_node_afaf7fab-f38a-4a5b-a940-e211ad04a008'].geometry}
              material={materials['tripo_material_afaf7fab-f38a-4a5b-a940-e211ad04a008']}
              position={[-12.55, 4.36, 6.58]}
              rotation={[0, 0.38, 0]}
              scale={3.45}
              castShadow
              receiveShadow
            />
          </HoverMesh>
        </DeferredRevealGroup>
        */}
        <group name="Sketchfab_model002" position={[-9.523, 2.941, 9.486]} rotation={[-Math.PI / 2, 0, -0.077]} scale={1.033}>
          <group name="39336dc9cb46483e8d9e86c656fd5660objcleanermaterialmerger" />
        </group>
        <group name="Sketchfab_model003" position={[25.621, -1.656, -4.746]} rotation={[-Math.PI / 2, 0, 0]} scale={0.002}>
          <group name="8da83dbbff734e0c83d2519cca3c0851fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode" position={[-0.001, 0, 0]}>
              <group name="Camera001" position={[3128.876, 1034.006, -3065.78]} rotation={[-3.14, -0.411, 3.07]}>
                <group name="Object_9" position={[-0.002, 0, 0.001]} />
              </group>
              <group name="Camera005" position={[-1327.729, 645.464, -340.835]} rotation={[0.162, 1.378, -0.223]} scale={0.692}>
                <group name="Object_9004" position={[0.001, 0, -0.002]} />
              </group>
              <group name="Camera007" position={[-3708.795, 1517.964, -1683.791]} rotation={[-0.002, 0.058, -0.073]} scale={[1.59, 1.498, 1.59]}>
                <group name="Object_9006" />
              </group>
              <group name="Camera009" position={[5203.794, 1831.818, 4900.756]} rotation={[3.089, -0.463, -2.946]} scale={[1.965, 1.5, 1.673]}>
                <group name="Object_9008" position={[0.001, 0, 0]} rotation={[-1.115, 1.465, 0.973]} />
              </group>
              <group name="Coconut-tree" position={[-0.001, 1245, 0]} />
              <group name="Directional_Light" position={[-514.911, 3255.172, -4877.482]} rotation={[2.035, -0.04, 3.047]}>
                <group name="Object_11" position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
                  <group name="Object_12" position={[0.001, 0, 0]} />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model004" position={[25.621, -1.656, -5.67]} rotation={[-Math.PI / 2, 0, -0.746]} scale={0.002}>
          <group name="8da83dbbff734e0c83d2519cca3c0851fbx001" position={[-0.001, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode001">
              <group name="Camera002" position={[3537.851, 1048.904, -1537.696]} rotation={[-3.14, -0.411, 3.07]}>
                <group name="Object_9001" position={[-0.001, 0, 0.001]} />
              </group>
              <group name="Camera006" position={[-2259.418, 706.156, 1440.541]} rotation={[0.149, 1.378, -0.234]} scale={0.692}>
                <group name="Object_9005" position={[0.001, 0, 0]} />
              </group>
              <group name="Coconut-tree001" position={[0, 1245, 0]} />
              <group name="Coconut-tree006" position={[3272.003, 732.753, -2338.44]} rotation={[2.877, -0.406, -3.079]} scale={[1.245, 1, 1.043]} />
              <group name="Directional_Light001" position={[-514.91, 3255.172, -4877.483]} rotation={[2.035, -0.04, 3.047]}>
                <group name="Object_11001" position={[0, -0.001, 0]} rotation={[Math.PI / 2, 0, 0]}>
                  <group name="Object_12001" position={[0.002, 0, 0.002]} />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model005" position={[25.458, -1.637, -6.212]} rotation={[-Math.PI / 2, 0, -0.746]} scale={0.001}>
          <group name="8da83dbbff734e0c83d2519cca3c0851fbx002" position={[0.001, -0.001, 0]} rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode002" position={[0, 0, -0.001]}>
              <group name="Camera003" position={[3606.734, 1048.903, -1589.289]} rotation={[-3.03, -0.399, 3.11]} scale={1.255}>
                <group name="Object_9002" position={[16.674, 0, -81.623]} rotation={[-0.092, 0.025, -0.042]} scale={0.775} />
              </group>
              <group name="Coconut-tree002" position={[0, 1245, -0.001]} />
              <group name="Coconut-tree004" position={[-2186.673, 750.212, -1796.5]} rotation={[-3.104, -0.969, -3.085]} scale={0.692} />
              <group name="Directional_Light002" position={[-452.867, 3255.172, -4957.916]} rotation={[1.946, 0.021, 2.988]} scale={0.975}>
                <group name="Object_11002" position={[22.177, 0.001, -82.602]} rotation={[1.564, -0.064, 0.043]} scale={1.275}>
                  <group name="Object_12002" position={[43.941, 0.001, 20.236]} rotation={[0.071, 0.005, 0.087]} scale={1.331} />
                </group>
              </group>
              <group name="Directional_Light004" position={[1160.638, 3538.839, -1424.458]} rotation={[0.927, 0.071, -0.554]} scale={[1.232, 0.987, 0.983]}>
                <group name="Object_11004" position={[22.177, 0, -82.602]} rotation={[0.312, -1.17, -1.473]} scale={1.275}>
                  <group name="Object_12004" position={[43.94, 0, 20.236]} rotation={[-1.135, -1.158, -1.251]} scale={1.331} />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model006" position={[25.019, -1.882, -7.298]} rotation={[-Math.PI / 2, 0, 0.266]} scale={0.001}>
          <group name="8da83dbbff734e0c83d2519cca3c0851fbx003" position={[0, 0.001, 0]} rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode003">
              <group name="Camera004" position={[3611.946, 1048.903, -1475.911]} rotation={[-3.017, -0.479, 3.044]} scale={0.953}>
                <group name="Object_9003" position={[1.587, 0, -86.567]} rotation={[0.022, 0.008, -0.036]} scale={1.283} />
              </group>
              <group name="Camera008" position={[3073.611, 1048.904, 127.67]} rotation={[-3.025, -0.352, 3.068]} scale={0.748}>
                <group name="Object_9007" position={[63.183, 0, 79.876]} rotation={[0.083, 0.02, 0.078]} scale={1.369} />
              </group>
              <group name="Coconut-tree003" position={[0, 1245, 0.001]} />
              <group name="Coconut-tree005" position={[1005.248, 787.343, -1648.979]} rotation={[-3.083, -0.969, -3.097]} scale={0.692} />
              <group name="Directional_Light003" position={[-514.909, 3255.172, -4877.481]} rotation={[2.035, -0.04, 3.047]}>
                <group name="Object_11003" position={[0.001, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
                  <group name="Object_12003" position={[0, 0, 0]} />
                </group>
              </group>
            </group>
          </group>
        </group>
        
        {/* COMMENTED OUT: Palm trees + water objects removed from ModelBeta.glb
        <DeferredRevealGroup
          active={showFoliage}
          rampStart={HEART_WINDOW.rampStart}
          rampDuration={HEART_WINDOW.rampDuration}
          yLift={0}
          scaleFrom={0.97}
          scaleTo={1}
          name="palm-oasis-cluster"
        >
        <PalmWindArmature swayIndex={0} name="Armature" position={[29.234, -1.429, -6.348]} rotation={[-0.247, -1.198, -0.177]} scale={0.699}>
          <primitive object={nodes.Bone} />
          <group name="trees012">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0002" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0002'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0002'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0002'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0002'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0002_1" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0002_1'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0002_1'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0002_1'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0002_1'].morphTargetInfluences} />
          </group>
        </PalmWindArmature>
        <PalmWindArmature swayIndex={1} name="Armature001" position={[26.896, -1.693, -7.433]} rotation={[0.046, -0.053, -0.197]} scale={0.969}>
          <primitive object={nodes.Bone_2} />
          <group name="trees024">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0003" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0003'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0003'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0003'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0003'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0003_1" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0003_1'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0003_1'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0003_1'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0003_1'].morphTargetInfluences} />
          </group>
        </PalmWindArmature>
        <PalmWindArmature swayIndex={2} name="Armature002" position={[26.804, -1.338, -8.612]} rotation={[-0.11, 0.575, 0.06]} scale={0.857}>
          <primitive object={nodes.Bone_4} />
          <group name="trees025">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0004" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0004'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0004'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0004'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0004'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0004_1" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0004_1'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0004_1'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0004_1'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0004_1'].morphTargetInfluences} />
          </group>
        </PalmWindArmature>
        <PalmWindArmature swayIndex={3} name="Armature003" position={[29.354, -1.104, -7.688]} rotation={[-0.126, -0.748, -0.086]} scale={0.688}>
          <primitive object={nodes.Bone_6} />
          <group name="trees026">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0005" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0005'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0005'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0005'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0005'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0005_1" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0005_1'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0005_1'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0005_1'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0005_1'].morphTargetInfluences} />
          </group>
        </PalmWindArmature>
        <PalmWindArmature swayIndex={4} name="Armature004" position={[28.817, -1.042, -8.57]} rotation={[-0.143, -0.008, 0.008]} scale={0.657}>
          <primitive object={nodes.Bone_8} />
          <group name="trees027">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_1" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_1'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_1'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_1'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_1'].morphTargetInfluences} />
          </group>
        </PalmWindArmature>
        <PalmWindArmature swayIndex={5} name="Armature005" position={[25.646, -1.271, -11.23]} rotation={[-0.158, 0.947, 0.128]} scale={0.869}>
          <primitive object={nodes.Bone_9} />
          <group name="trees028">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_2" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_2'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_2'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_2'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_2'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_3" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_3'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_3'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_3'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_3'].morphTargetInfluences} />
          </group>
        </PalmWindArmature>
        <PalmWindArmature swayIndex={6} name="Armature006" position={[26.483, -1.297, -7.863]} rotation={[-0.106, 0.153, 0.054]} scale={0.586}>
          <primitive object={nodes.Bone_10} />
          <group name="trees029">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_4" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_4'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_4'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_4'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_4'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_5" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_5'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_5'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_5'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_5'].morphTargetInfluences} />
          </group>
        </PalmWindArmature>
        <PalmWindArmature swayIndex={7} name="Armature007" position={[27.034, -0.898, -11.166]} rotation={[0.475, 1.093, -0.146]} scale={0.759}>
          <primitive object={nodes.Bone_11} />
          <group name="trees030">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_6" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_6'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_6'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_6'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_6'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_7" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_7'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_7'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_7'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_7'].morphTargetInfluences} />
          </group>
        </PalmWindArmature>
        <PalmWindArmature swayIndex={8} name="Armature008" position={[27.393, -1.429, -3.185]} rotation={[0.081, 0.119, -0.046]} scale={0.628}>
          <primitive object={nodes.Bone_1} />
          <group name="trees001">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0002_2" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0002_2'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0002_2'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0002_2'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0002_2'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0002_3" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0002_3'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0002_3'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0002_3'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0002_3'].morphTargetInfluences} />
          </group>
        </PalmWindArmature>
        <PalmWindArmature swayIndex={9} name="Armature009" position={[29.063, -1.693, -4.054]} rotation={[0.051, -0.465, -0.177]} scale={0.666}>
          <primitive object={nodes.Bone_3} />
          <group name="trees002">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0003_2" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0003_2'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0003_2'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0003_2'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0003_2'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0003_3" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0003_3'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0003_3'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0003_3'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0003_3'].morphTargetInfluences} />
          </group>
        </PalmWindArmature>
        <PalmWindArmature swayIndex={10} name="Armature010" position={[29.784, -1.338, -5.261]} rotation={[-0.096, 0.29, 0.027]} scale={0.694}>
          <primitive object={nodes.Bone_5} />
          <group name="trees003">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0004_2" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0004_2'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0004_2'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0004_2'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0004_2'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0004_3" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0004_3'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0004_3'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0004_3'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0004_3'].morphTargetInfluences} />
          </group>
        </PalmWindArmature>
        <PalmWindArmature swayIndex={11} name="Armature011" position={[29.259, -1.104, -2.096]} rotation={[-2.991, -0.914, -3.022]} scale={0.984}>
          <primitive object={nodes.Bone_7} />
          <group name="trees004">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0005_2" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0005_2'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0005_2'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0005_2'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0005_2'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0005_3" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0005_3'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0005_3'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0005_3'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0005_3'].morphTargetInfluences} />
          </group>
        </PalmWindArmature>
        <PalmWindArmature swayIndex={12} name="Armature012" position={[30.545, -1.042, -3.294]} rotation={[-0.199, -0.764, -0.129]} scale={0.635}>
          <primitive object={nodes.Bone_12} />
          <group name="trees005">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_8" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_8'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_8'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_8'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_8'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_9" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_9'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_9'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_9'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_9'].morphTargetInfluences} />
          </group>
        </PalmWindArmature>
        <PalmWindArmature swayIndex={13} name="Armature013" position={[28.543, -1.271, -7.774]} rotation={[-0.571, -1.4, -0.564]} scale={0.6}>
          <primitive object={nodes.Bone_13} />
          <group name="trees006">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_10" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_10'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_10'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_10'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_10'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_11" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_11'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_11'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_11'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_11'].morphTargetInfluences} />
          </group>
        </PalmWindArmature>
        <PalmWindArmature swayIndex={14} name="Armature014" position={[29.488, -1.297, -4.369]} rotation={[-0.112, 0.357, 0.077]} scale={0.929}>
          <primitive object={nodes.Bone_14} />
          <group name="trees007">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_12" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_12'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_12'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_12'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_12'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_13" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_13'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_13'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_13'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_13'].morphTargetInfluences} />
          </group>
        </PalmWindArmature>
        <PalmWindArmature swayIndex={15} name="Armature015" position={[29.93, -0.936, -6.09]} rotation={[0.213, -0.104, 0.304]} scale={0.86}>
          <primitive object={nodes.Bone_15} />
          <group name="trees008">
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_14" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_14'].geometry} material={materials['Coconut_tree-Trunk']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_14'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_14'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_14'].morphTargetInfluences} />
            <skinnedMesh name="Coconut-tree_Coconut_tree-Trunk_0006_15" geometry={nodes['Coconut-tree_Coconut_tree-Trunk_0006_15'].geometry} material={materials['Cononute_tree-Leafs']} skeleton={nodes['Coconut-tree_Coconut_tree-Trunk_0006_15'].skeleton} morphTargetDictionary={nodes['Coconut-tree_Coconut_tree-Trunk_0006_15'].morphTargetDictionary} morphTargetInfluences={nodes['Coconut-tree_Coconut_tree-Trunk_0006_15'].morphTargetInfluences} />
          </group>
        </PalmWindArmature>
          <group name="water">
            <mesh
              name="Plane002"
              geometry={nodes.Plane002.geometry}
              material={oasisWaterMat}
              position={[17.951, -2.014, -8.31]}
              rotation={[0, -1.562, 0]}
              scale={[3.271, 3.271, 5.328]}
              receiveShadow
            />
          </group>
        </DeferredRevealGroup>
        */}

        {/* <mesh name="Plane029" geometry={nodes.Plane029.geometry} material={materials['Material.002']} position={[-20.66, 7.914, 7.355]} rotation={[0.536, -0.307, 0.002]} scale={[14.382, 9.208, 11.667]} />
        <mesh name="Plane026" geometry={nodes.Plane026.geometry} material={materials['Material.002']} position={[-4.622, 4.389, 12.748]} rotation={[1.547, -0.127, 0.342]} scale={[6.008, 3.846, 4.874]} />
        <mesh name="Plane027" geometry={nodes.Plane027.geometry} material={materials['Material.002']} position={[1.205, 3.714, 0.55]} rotation={[1.445, 0.002, 0.139]} scale={[10.616, 11.655, 7.05]} />
        <mesh name="Plane028" geometry={nodes.Plane028.geometry} material={materials['Material.002']} position={[20.812, 4.112, 9.064]} rotation={[1.488, 0.07, 0.784]} scale={[18.243, 11.726, 6.453]} />
        <mesh name="Plane031" geometry={nodes.Plane031.geometry} material={materials['Material.002']} position={[11.572, 6.536, 20.687]} rotation={[1.637, -0.016, -0.4]} scale={[18.322, 11.731, 14.864]} />
        <mesh name="Plane033" geometry={nodes.Plane033.geometry} material={materials['Material.002']} position={[-13.591, 4.867, 16.789]} rotation={[1.004, -0.325, 0.385]} scale={[5.747, 2.89, 3.103]} />
        {/* <mesh name="Plane034" geometry={nodes.Plane034.geometry} material={materials['Material.002']} position={[-7.656, 4.542, 19.329]} rotation={[1.004, -0.325, 0.385]} scale={[5.747, 2.89, 3.834]} /> */}
        
        //deert plane
        <mesh
          ref={sandMorphPlaneRef}
          name="Plane"
          geometry={nodes.Plane.geometry}
          material={materials['Material.003'] || materials['Material.001']}
          morphTargetDictionary={nodes.Plane.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane.morphTargetInfluences}
          scale={4.298}
        />
        //
<group name='backgroundsand'>
 <group name='backgroundsand'>
  <mesh name="Plane003" geometry={nodes.Plane003.geometry} position={[48.288, -2.603, -17.238]} rotation={[Math.PI, -1.567, Math.PI]} scale={4.298}>
    <meshStandardMaterial {...sandTerrainMatProps} />
  </mesh>
  <mesh name="Plane004" geometry={nodes.Plane004.geometry} position={[48.288, -1.757, -64.814]} rotation={[Math.PI, -0.095, Math.PI]} scale={4.298}>
    <meshStandardMaterial {...sandTerrainMatProps} />
  </mesh>
  <mesh name="Plane005" geometry={nodes.Plane005.geometry} position={[102.725, 0.545, -41.628]} rotation={[0.093, 0.021, 0.036]}>
    <meshStandardMaterial {...sandTerrainMatProps} />
  </mesh>
  <mesh name="Plane025" geometry={nodes.Plane025.geometry} position={[102.725, 0.545, -27.086]} rotation={[0.093, 0.021, 0.036]}>
    <meshStandardMaterial {...sandTerrainMatProps} />
  </mesh>
  <mesh name="Plane006" geometry={nodes.Plane006.geometry} position={[91.214, 0.813, -89.131]} rotation={[-3.108, -0.636, 3.031]} scale={[1.451, 0.784, 1.46]}>
    <meshStandardMaterial {...sandTerrainMatProps} />
  </mesh>
  <mesh name="Plane007" geometry={nodes.Plane007.geometry} position={[44.341, -3.504, -114.639]} rotation={[-2.676, 1.51, 2.546]} scale={[1.034, 1.316, 1.029]}>
    <meshStandardMaterial {...sandTerrainMatProps} />
  </mesh>
  <mesh name="Plane008" geometry={nodes.Plane008.geometry} position={[1.209, -5.004, -114.467]} rotation={[-1.803, 1.543, 1.672]} scale={[1.366, 1.516, 1.362]}>
    <meshStandardMaterial {...sandTerrainMatProps} />
  </mesh>
  <mesh name="Plane009" geometry={nodes.Plane009.geometry} position={[-40.38, -5.351, -114.639]} rotation={[-0.027, 0.006, -0.131]} scale={[1.034, 1.316, 1.029]}>
    <meshStandardMaterial {...sandTerrainMatProps} />
  </mesh>
  <mesh name="Plane010" geometry={nodes.Plane010.geometry} position={[-40.38, -5.351, -51.111]} rotation={[-0.027, 0.006, -0.131]} scale={[1.049, 2.168, 1.029]}>
    <meshStandardMaterial {...sandTerrainMatProps} />
  </mesh>
  <mesh name="Plane011" geometry={nodes.Plane011.geometry} position={[-13.766, -1.497, -103.757]} rotation={[-0.027, 0.006, -0.131]} scale={[1.034, 1.316, 1.029]}>
    <meshStandardMaterial {...sandTerrainMatProps} />
  </mesh>
  <mesh
    ref={sandMorphPlane001Ref}
    name="Plane001"
    geometry={nodes.Plane001.geometry}
    morphTargetDictionary={nodes.Plane001.morphTargetDictionary}
    morphTargetInfluences={nodes.Plane001.morphTargetInfluences}
    position={[-6.375, -0.341, -59.446]}
    rotation={[Math.PI, 0, Math.PI]}
    scale={4.298}
  >
    <meshStandardMaterial {...sandTerrainMatProps} />
  </mesh>
</group>
    
</group>
        {/* COMMENTED OUT: Oasis pool object removed from ModelBeta.glb
        <DeferredRevealGroup
          active={showFoliage}
          rampStart={HEART_WINDOW.rampStart}
          rampDuration={HEART_WINDOW.rampDuration}
          yLift={0}
          scaleFrom={0.97}
          scaleTo={1}
          name="oasis-plane013"
        >
          <HoverMesh
            label={PROTOTYPE_HOVER_OASIS_POOL.realm}
            chipStyle="stacked"
            screenSizeMode="fixed"
            htmlPosition={[-2.42, 0.58, 0]}
            stackedMaxWidth={360}
            stackedPadding="12px 24px 14px"
            onHoverChange={setHoverUi}
            onSelect={() => onHoverSelect?.(PROTOTYPE_HOVER_OASIS_POOL)}
          >
            <mesh
              name="Plane013"
              geometry={nodes.Plane013.geometry}
              material={oasisWaterMat}
              morphTargetDictionary={nodes.Plane013.morphTargetDictionary}
              morphTargetInfluences={nodes.Plane013.morphTargetInfluences}
              position={[21.475, -1.613, -5.666]}
              scale={3.814}
              receiveShadow
            />
          </HoverMesh>
        </DeferredRevealGroup>
        */}

      </group>
      </RevealGroupBatchRoot>
    </group>
  )
}

useGLTF.preload('/ModelBeta.glb')
